# If you're running this on localhost, you can leave the uri as is.
# If not, please create a free cluster on https://www.mongodb.com/atlas
# and replace the uri with the connection string provided when clicking 'Connect'.
# Make sure to whitelist your IP address in the network access settings.
mongo-uri: "mongodb://localhost:27017"
# Replace this webhook with your own, if you don't want to send logs to discord, set it to ""
discord-webhook: "https://discord.com/api/webhooks/1268163186486411345/z_v5wT-e6QveEATDGXRgzCao1D7_ARqQbx6UwkZsEvd-gvIR1FloiXbrOKeIa5SmQ8tk"

general-settings:
  prefix: "" # TODO
  debug: true # if set to true, you can purchase your own listings
  addToInvIfOnline: true # setting this to false will put the item into their player's 'collect' even if they are online
  minPrice: 100 # WARNING: negative values are interpreted as 0
  maxPrice: 1000000
  cooldown: 0 # in seconds
  duration: 7d0h0m # how long you want the listing to last
  tax: 0 # in perecent, i.e 20 = 20%
  maxListings: 5
  priceAsInteger: false


blackmarket:
  discount-amount: 50 # % amount
  cooldown: 5 # in minutes
#  automatic: true
