# If you're running this on localhost, you can leave the uri as is.
# If not, please create a free cluster on https://www.mongodb.com/atlas
# and replace the uri with the connection string provided when clicking 'Connect'.
# Make sure to whitelist your IP address in the network access settings.
mongo-uri: "mongodb+srv://admin:admin@data.bpuxsv3.mongodb.net/?retryWrites=true&w=majority&appName=data"
# You can create a free redis deployment using https://railway.app/create
redis-uri: "redis://default:AgrgBkMfQEDVQquEiTVzcSJTpEGdAtBX@viaduct.proxy.rlwy.net:26208"
discord:
  enableMessages: false
  # replace this with your own, or disable messages
  webhook: "https://discord.com/api/webhooks/1268163186486411345/z_v5wT-e6QveEATDGXRgzCao1D7_ARqQbx6UwkZsEvd-gvIR1FloiXbrOKeIa5SmQ8tk"

general-settings:
  addToInvIfOnline: true # setting this to false will put the item into their player's 'collect' even if they are online
  minPrice: 100 # WARNING: negative values are interpreted as 0
  maxPrice: 10000000
  duration: 7d0h0m0s # how long you want the listing to last
  maxTransactions: 10

command-messages:
  noSellPermission: "&cYou do not have permission to sell items."
  noCollectPermission: "&cYou do not have permission to collect items."
  noViewPermission: "&cYou do not have permission to view the marketplace."
  noBlackmarketPermission: "&cYou do not have permission to generate the blackmarket."
  noTransactionPermission: "&cYou do not have permission to view your transaction history."
  noCollectItems: "&cYou have no items to collect."
  hasCollectItems: "&aYou have items to collect. Use /collect to collect them."
  mustSpecifyPrice: "&cYou must specify a price. For example: &e/sell 100"
  priceTooLow: "&cThe price must be at least &e%minPrice%"
  priceTooHigh: "&cThe maximum price is &e%maxPrice%"
  invalidItem: "&cYou must be holding the item you want to sell."
  noTransactions: "&cYou have no transaction history."
  itemSold: "&aYou sold %item% for &e%price%&a."
  itemPurchased: "&aYou bought %item% for &e%price%&a."
  moreThanMaxTransactions: "&7You have &e%totalTransactions% &7transactions, here's your past &e%maxTransactions%&7:"
  lessThanMaxTransactions: "&7You have &e%totalTransactions% &7transactions:"
  balanceTooLow: "&cYou do not have enough money to purchase this item."
  alreadyPurchased: "&cThis listing is no longer available."
  purchaseCancelled: "&cYou have cancelled the purchase."

messages:
  prefix: "&7[&eMarketplace&7] &r"
  listings:
    announce: false
    announce-message: "&a&l%seller% &7has listed %item% &7for &e%price% &7on the marketplace!"
    message: "You listed &7%item% &7for &e%price% &7on the marketplace!"
  purchases:
    announce: false
    announce-message: "&a&l%buyer% &7has purchased %item% from &a&l%seller% &7for &e%price% &7on the marketplace!"
    message: "You bought &7%item% &7for &e%price% &7from &a&l%seller%."

# You can use any material name from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
buttons:
  previous: "RED_CONCRETE"
  next: "LIME_CONCRETE"
  confirm: "LIME_STAINED_GLASS_PANE"
  back: "RED_STAINED_GLASS_PANE"
  collect: "BLACK_CONCRETE"
  border: "BLACK_STAINED_GLASS_PANE"
  collect-border: "LIGHT_BLUE_STAINED_GLASS_PANE"
  blackmarket-border: "PURPLE_STAINED_GLASS_PANE"

blackmarket:
  discount-amount: 50 # % amount
  amountOfItems: 10 # max amount is 10
  refreshRate: 1 # the amount of minutes before the blackmarket refreshes
  announce: true
  announce-message: "&7The blackmarket has been refreshed!"