mongo-uri: "mongodb+srv://connorwitmer34:<password>@data.bpuxsv3.mongodb.net/?retryWrites=true&w=majority&appName=data"

general-settings:
  prefix: "" # TODO
  updateInterval: 20 # 20 ticks = 1 second
  minPrice: 100.00
  maxPrice: 1000000.00
  cooldown: 0 # in seconds
  duration: 7d0h0m
  tax: 0 # in perecent, i.e 20 = 20%
  maxListings: 5
  priceAsInteger: false


blackmarket:
  discount-amount: 50 # % amount
  cooldown: 5 # in minutes
#  automatic: true
